---
title: "Spatial Analysis Document"
author: "Samuel Wolf"
date: "March 23, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries
```{r libraries, message=FALSE, warning=FALSE}
library(knitr)
library(tidyverse)
library(raster)
library(sp)
library(dismo)
library(maptools)
library(tidyr)
```


## Species selection
Here I am going to use the species [Varanus komodoensis](https://en.wikipedia.org/wiki/Komodo_dragon) and [Basiliscus basiliscus](https://en.wikipedia.org/wiki/Common_basilisk). 


### Occurrence data from gbif
```{r message=FALSE, warning=FALSE}
# Geographic occurrence data for both of our lizards
Komodo <-gbif("Varanus","komodoensis")
Basilisk <-gbif("Basiliscus","basiliscus")
```

### Cleaning occurrence
```{r}
# Delete occurrence without geographic information
Komodo<-
  Komodo %>% 
  filter(!is.na(lon)&!is.na(lat))
Basilisk<-
  Basilisk %>% 
  filter(!is.na(lon)&!is.na(lat))

## Get rid of duplicate occurrences
dups=duplicated(Komodo[, c("lon", "lat")])
Komodo <-Komodo[!dups, ]
dups=duplicated(Basilisk[, c("lon", "lat")])
Basilisk <-Basilisk[!dups, ]
```

## Extract climatic variables
```{r}
# using the raster package
bio_ly <- getData("worldclim",var="bio",res=10, path="./data/")

tempRast <- bio_ly$bio1/10
precipRast <- bio_ly$bio12


##Convert Ocurrence data to spatial points 
Komodo_geo<-Komodo
coordinates(Komodo_geo)<-~lon + lat
Basilisk_geo<-Basilisk
coordinates(Basilisk_geo)<-~lon + lat

## Changing projection (tempRast and precipiRast have the same projection)
proj4string(Komodo_geo)<-proj4string(tempRast)
proj4string(Basilisk_geo)<-proj4string(tempRast)


## Extracting Temperature and precipitation
## using the expression 'raster::extract' I make sure that the function that I am calling is from the raster package. Extract as a function is also found in the tidyr package.
Komodo$temp<-raster::extract(tempRast,Komodo_geo)
Komodo$precip<-raster::extract(precipRast,Komodo_geo)
Basilisk$temp<-raster::extract(tempRast,Basilisk_geo)
Basilisk$precip<-raster::extract(precipRast,Basilisk_geo)
```


## Plot species occurrences

```{r}
## Plotting Komodo climatic variable and coordinates
new_map<-crop(tempRast,extent(Komodo_geo))

plot(new_map)
points(Komodo_geo,pch=20,col=alpha("blue",0.5))
```
```{r}
## Plotting Basilisk climatic variable and coordinates
new_map<-crop(tempRast,extent(Basilisk_geo))

plot(new_map)
points(Basilisk_geo,pch=20,col=alpha("blue",0.5))
```


## Species climatic distribution

```{r message=FALSE, warning=FALSE}
# Komodo climatic distribution
hist(Komodo$temp)

Komodo %>% 
  ggplot(aes(precip)) +
  geom_density(color="darkblue", fill="lightblue")
```


```{r message=FALSE, warning=FALSE}
# Basilisk climatic distribution
hist(Basilisk$temp)

Basilisk %>% 
  ggplot(aes(precip)) +
  geom_density(color="darkblue", fill="lightblue")
```